//bool select_save_location(FSSpec* to_save_ptr);
//void save_file(FSSpec to_save);
//void load_file();
void leave_town();
//long do_waterfall(long flag);
short init_data(short flag);
//long open_pref_file();
//void make_pref_file(FSSpec pref);
//void save_prefs();
void remove_party_from_scen();
void load_base_item_defs();
bool load_scen_item_defs(std::string scen_name);
