//
//  scen.menus.h
//  BoE
//
//  Created by Celtic Minstrel on 14-04-24.
//
//

#ifndef BoE_scen_menus_h
#define BoE_scen_menus_h

void init_menubar();
void shut_down_menus(short mode);
void update_edit_menu();

enum class eMenu {
	NONE, ABOUT, PREFS, QUIT, FRILL, UNFRILL,
	FILE_NEW, FILE_OPEN, FILE_CLOSE, FILE_SAVE, FILE_SAVE_AS, FILE_REVERT,
	EDIT_UNDO, EDIT_REDO, EDIT_CUT, EDIT_COPY, EDIT_PASTE, EDIT_DELETE, EDIT_SELECT_ALL,
	HELP_TOC, HELP_START, HELP_TEST, HELP_DIST, HELP_CONTEST,
	// Scenario menu
	LAUNCH_HERE, LAUNCH_START, LAUNCH_ENTRANCE, TOWN_CREATE, OUT_RESIZE,
	SCEN_DETAILS, SCEN_ADV_DETAILS, SCEN_INTRO, TOWN_START,
	SCEN_SPECIALS, SCEN_TEXT, SCEN_JOURNALS, TOWN_IMPORT, OUT_IMPORT,
	SCEN_SAVE_ITEM_RECTS,
	TOWN_VARYING, SCEN_TIMERS, SCEN_ITEM_SHORTCUTS, TOWN_DELETE,
	SCEN_DATA_DUMP, SCEN_TEXT_DUMP,
	SCEN_PICS, SCEN_SHEETS, SCEN_SNDS,
	// Town menu
	TOWN_DETAILS, TOWN_WANDERING, TOWN_BOUNDARIES, TOWN_AREAS,
	TOWN_ITEMS_RANDOM, TOWN_ITEMS_NOT_PROPERTY, TOWN_ITEMS_CLEAR,
	TOWN_SPECIALS, TOWN_TEXT, TOWN_SIGNS, TOWN_ADVANCED, TOWN_TIMERS,
	// Outdoors menu
	OUT_DETAILS, OUT_WANDERING, OUT_ENCOUNTERS, OUT_AREAS, OUT_START,
	OUT_SPECIALS, OUT_TEXT, OUT_SIGNS,
};

void handle_menu_choice(eMenu item_hit);

#endif
