
Import("env")

common_classes = Split("""
	estreams.cpp
	item.cpp
	location.cpp
	monster.cpp
	outdoors.cpp
	scenario.cpp
	shop.cpp
	special.cpp
	spell.cpp
	talking.cpp
	terrain.cpp
	town.cpp
	vehicle.cpp
""")

party_classes = Split("""
	creatlist.cpp
	creature.cpp
	living.cpp
	party.cpp
	pc.cpp
	universe.cpp
""")

common = env.StaticLibrary("#build/lib/common", common_classes)
party = env.StaticLibrary("#build/lib/common_party", party_classes)

ret = (common, party)

Return("ret")
