#---------------------------------#
#      general configuration      #
#---------------------------------#
 
version: 0.9-build-{build}


#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      SFML_PATH:      C:\SFML-VS2017
      SFML_VERSION:   latest
      GENERATOR:      Visual Studio 15 2017 Win64
      BUILD_TYPE:     Debug
      SHARED_LIBS:    FALSE
      BUILD_TESTS:    TRUE
      BUILD_EXAMPLES: FALSE
      FAST_BUILD:     FALSE
      BUILD_FOLDER:   build-VS2017-Win32

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      SFML_PATH:      C:\SFML-VS2015
      SFML_VERSION:   2.5.0
      GENERATOR:      Visual Studio 14 2015
      BUILD_TYPE:     Release
      SHARED_LIBS:    TRUE
      BUILD_TESTS:    FALSE
      BUILD_EXAMPLES: TRUE
      FAST_BUILD:     TRUE
      BUILD_FOLDER:   build-VS2015-Win64

clone_depth: 3

matrix:
  fast_finish: true

cache:
  - C:\SFML-VS2017 -> .appveyor.yml
  - C:\SFML-VS2015 -> .appveyor.yml


install:
- IF "%SFML_VERSION%" == "latest" (
    git clone https://github.com/SFML/SFML --depth 1 --branch "2.6.x" &&
    cd SFML &&
    IF EXIST "%SFML_PATH%\lib" (
      IF EXIST "%SFML_PATH%\revision_cache" (
        git rev-parse HEAD > revision &&
        fc revision "%SFML_PATH%\revision_cache" > nul || (exit 0) &&
        IF %ERRORLEVEL% EQU 0 (
          echo Using cached SFML directory
        ) ELSE (
          echo Rebuilding SFML, cached version is out of date &&
          cmake -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX=%SFML_PATH% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DBUILD_SHARED_LIBS=%SHARED_LIBS% . &&
          cmake --build . --target install --config %BUILD_TYPE% -- /m &&
          git rev-parse HEAD > "%SFML_PATH%\revision_cache"
        )
      ) ELSE (
        echo Rebuilding SFML, cached version is missing revision_cache file &&
        cmake -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX=%SFML_PATH% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DBUILD_SHARED_LIBS=%SHARED_LIBS% . &&
        cmake --build . --target install --config %BUILD_TYPE% -- /m &&
        git rev-parse HEAD > "%SFML_PATH%\revision_cache"
      )
    ) ELSE (
      echo Rebuilding SFML, no cache available &&
      cmake -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX=%SFML_PATH% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DBUILD_SHARED_LIBS=%SHARED_LIBS% . &&
      cmake --build . --target install --config %BUILD_TYPE% -- /m &&
      git rev-parse HEAD > "%SFML_PATH%\revision_cache"
    )
  ) ELSE IF NOT "%SFML_PATH%" == "C:\SFML" (
    IF NOT EXIST %SFML_PATH% (
      appveyor DownloadFile https://github.com/SFML/SFML/archive/%SFML_VERSION%.zip -FileName SFML.zip &&
      7z x SFML.zip > nul &&
      move SFML-%SFML_VERSION% %SFML_PATH% > nul &&
      cd %SFML_PATH% &&
      mkdir lib &&
      cmake -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX=%SFML_PATH% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DBUILD_SHARED_LIBS=%SHARED_LIBS% . &&
      cmake --build . --target install --config %BUILD_TYPE% -- /m
    )
  )


#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - cd C:\projects\tgui
  - IF NOT "%SFML_PATH%" == "C:\SFML" (
      mkdir %BUILD_FOLDER% &&
      cd %BUILD_FOLDER% &&
      cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DTGUI_SHARED_LIBS=%SHARED_LIBS% -DTGUI_BUILD_TESTS=%BUILD_TESTS% -DTGUI_ENABLE_DRAW_TESTS=%BUILD_TESTS% -DTGUI_BUILD_EXAMPLES=%BUILD_EXAMPLES% -DTGUI_BUILD_GUI_BUILDER=FALSE -DTGUI_OPTIMIZE_SINGLE_BUILD=%FAST_BUILD% -DSFML_DIR=%SFML_PATH%\lib\cmake\SFML .. &&
      msbuild tgui.sln /p:Configuration=%BUILD_TYPE% /m &&
      cd .. &&
      IF "%BUILD_TESTS%"=="TRUE" (
        cd %BUILD_FOLDER%\tests\%BUILD_TYPE% &&
        tests.exe
      )
    )


#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
- provider: GitHub
  tag: nightly_build
  release: 'Nightly build'
  description: 'Latest nightly build binary'
  draft: false
  prerelease: true
  force_update: true
  auth_token:
    secure: rVxk6OWc0JLdMi5VXVuWLAvlT1whbHHHNBPgcaJxZoYXJlwK0ixT1w1XdF5S7DBH
  on:
    branch: 0.9
    APPVEYOR_REPO_TAG: false


#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/1feed1f155b2a41e6a62
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
