void draw_one_terrain_spot (short i,short j,short terrain_to_draw,short dest);
void draw_monsters();
void play_see_monster_str(unsigned short m);
void draw_pcs(location center,short mode);
void draw_items();
void draw_outd_boats(location center);
void draw_town_boat(location center) ;
void draw_fields();
void draw_spec_items();
void draw_sfx();
void draw_one_field(unsigned char flag,short source_x,short short_y);
void draw_one_spec_item(unsigned char flag,short source_x,short short_y);
void draw_party_symbol(short mode,location center);
Rect get_terrain_template_rect (ter_num_t type_wanted);
Rect return_item_rect(short wanted);
Rect get_monster_rect (unsigned char type_wanted,short mode) ;
Rect get_monster_template_rect (unsigned short type_wanted,short mode,short which_part) ;
Rect get_item_template_rect (short type_wanted);
bool is_fluid(ter_num_t ter_type);
bool is_shore(ter_num_t ter_type);
bool is_wall(ter_num_t ter_type);
bool is_ground(ter_num_t ter_type);
//void make_town_trim(short mode);
//void make_out_trim();
char get_fluid_trim(location where,ter_num_t ter_type);
void check_if_monst_seen(unsigned short m_num);
void adjust_monst_menu();
