class cDialog;
void init_party(short mode) __attribute__((deprecated));
void init_party_scen_data() __attribute__((deprecated));
void make_boats();
bool create_pc(short spot,cDialog* parent_num);
bool take_sp(short pc_num,short amt);
void heal_pc(short pc_num,short amt);
void heal_party(short amt);
void cure_pc(short pc_num,short amt);
void cure_party(short amt);
void curse_pc(short which_pc,short how_much);
void dumbfound_pc(short which_pc,short how_much);
void disease_pc(short which_pc,short how_much);
void sleep_pc(short which_pc,short how_much,eStatus what_type,short adjust);
void slow_pc(short which_pc,short how_much);
void web_pc(short which_pc,short how_much);
void increase_light(short amt);
void restore_sp_pc(short pc_num,short amt);
void restore_sp_party(short amt);
void award_party_xp(short amt);
void award_xp(short pc_num,short amt);
void drain_pc(short which_pc,short how_much);
short mage_lore_total();
bool poison_weapon( short pc_num, short how_much,short safe);
bool is_weapon(short pc_num,short item);
void cast_spell(short type,short situation);
bool repeat_cast_ok(short type);
void give_party_spell(short which);
void do_mage_spell(short pc_num,short spell_num);
void do_priest_spell(short pc_num,short spell_num);
void cast_town_spell(location where);
void sanctify_space(location where);
void crumble_wall(location where);
void do_mindduel(short pc_num,cCreature *monst);
void dispel_fields(short i,short j,short mode);
bool pc_can_cast_spell(short pc_num,short type,short spell_num);
short pick_spell(short pc_num,short type,short situation) ;
short stat_adj(short pc_num,short which);
void set_town_spell(short s_num,short who_c);
void do_alchemy();
short alch_choice(short pc_num);
bool pick_pc_graphic(short pc_num,short mode,cDialog* parent_num);
bool pick_pc_name(short pc_num,cDialog* parent)  ;
m_num_t pick_trapped_monst()  ;
bool flying() ;
void acid_pc(short which_pc,short how_much);
void poison_pc(short which_pc,short how_much);
void poison_party(short how_much);
void affect_pc(short which_pc,eStatus type,short how_much);
void affect_party(eStatus type,short how_much);
void void_sanctuary(short pc_num);
void hit_party(short how_much,eDamageType damage_type);
void slay_party(eMainStatus mode);
bool damage_pc(short which_pc,short how_much,eDamageType damage_type,eMonsterType type_of_attacker, short sound_type);
void kill_pc(short which_pc,eMainStatus type);
void set_pc_moves();
void take_ap(short num);
short cave_lore_present();
short woodsman_present();
void print_spell_cast(short spell_num,short which);
void put_party_in_scen(std::string scen_name);

// This is defined in pc.editors.cpp since it is also used by the character editor
bool spend_xp(short pc_num, short mode, cDialog* parent);
