void init_screen_locs();
Boolean prime_time();
Boolean handle_action(EventRecord event);
Boolean someone_awake();
void flash_rect(Rect to_flash);
void flash_round_rect(Rect to_flash,short radius);
void button_flash_rect(Rect to_flash);
void handle_menu_spell(short spell_picked,short spell_type) ;
void initiate_outdoor_combat(short i);
void initiate_redraw();
Boolean handle_keystroke(char chr,char chr2,EventRecord event);
void menu_activate( short type);
void do_load();
void post_load();
void do_save(short mode);
void increase_age();
void handle_cave_lore();
void switch_pc(short which);
void drop_pc(short which);
void handle_death();
void start_new_game();
location get_cur_direction(Point the_point);
Boolean outd_move_party(location destination,Boolean forced);
Boolean town_move_party(location destination,short forced);
Boolean someone_poisoned();
short nearest_monster();
void setup_outdoors(location where);
short get_outdoor_num();
short count_walls(location loc);
Boolean is_sign(unsigned char ter);
