void init_town(short size);
void init_out();
void edit_placed_monst(short which_m);
void edit_placed_monst_event_filter (short item_hit);
Boolean get_placed_monst_in_dlog();
void put_placed_monst_in_dlog();
creature_start_type edit_placed_monst_adv(creature_start_type monst_record);
void edit_placed_monst_adv_event_filter (short item_hit);
Boolean get_placed_monst_adv_in_dlog();
void put_placed_monst_adv_in_dlog();
void edit_sign(short which_sign,short picture);
void edit_sign_event_filter (short item_hit);
Boolean save_out_strs();
void put_out_strs_in_dlog();
void edit_out_strs_event_filter (short item_hit);
void edit_out_strs();
Boolean save_town_strs();
void put_town_strs_in_dlog();
void edit_town_strs_event_filter (short item_hit);
void edit_town_strs();
void pick_town_num_event_filter (short item_hit);
short pick_town_num(short which_dlog,short def);
void change_ter(short *change_from,short *change_to,short *chance);
void change_ter_event_filter (short item_hit);
void edit_out_wand(short mode);
void edit_out_wand_event_filter (short item_hit);
Boolean get_out_wand_in_dlog();
void put_out_wand_in_dlog();
void outdoor_details_event_filter (short item_hit);
void outdoor_details();
void edit_town_details();
void edit_town_details_event_filter (short item_hit);
void put_town_details_in_dlog();
Boolean save_town_details();
void edit_town_events();
void edit_town_events_event_filter (short item_hit);
void put_town_events_in_dlog();
Boolean save_town_events();
void edit_advanced_town();
void edit_advanced_town_event_filter (short item_hit);
void put_advanced_town_in_dlog();
Boolean save_advanced_town();
void edit_basic_dlog(short which_node);
void edit_basic_dlog_event_filter (short item_hit);
void put_basic_dlog_in_dlog();
Boolean save_basic_dlog();
void edit_talk_node(short which_node,short parent_num);
void edit_talk_node_event_filter (short item_hit);
void put_talk_node_in_dlog();
Boolean save_talk_node();
void pick_out_event_filter (short item_hit);
short pick_out(location default_loc);
void pick_import_town_event_filter (short item_hit);
short pick_import_town(short which_dlog,short def);
Boolean new_town(short which_town);
void new_town_event_filter (short item_hit);
void edit_placed_item_event_filter (short item_hit);
void edit_placed_item(short which_i);

void delete_last_town();
void edit_town_wand_event_filter (short item_hit);
void edit_town_wand();
