
import os.path as path

Import("env platform")

if str(platform) != "win32":
	print(f"Error: Building for {platform}, but trying to create a Windows installer package")

env.Depends("data.nsi", ["gen-data.py", "#build/Blades of Exile/data"])

env.Command("data.nsi", "../Blades of Exile",
	action = 'python build/pkg/gen-data.py ${SOURCE.abspath} > $TARGET'
)

env.Depends("Install-OBoE.exe", [
	"#build/Blades of Exile",
	"data.nsi",
	"fileassoc.nsh"
])

if 'msvc' in env["TOOLS"]:
	makensis = "makensis /DMSVC"
else:
	makensis = "makensis"

env.Command("Install-OBoE.exe", "main.nsi", action = makensis + " /V2 $SOURCE")
