
Import("env platform")

tools = Split("""
	fileio_scen.cpp
	fileio.cpp
	graphtool.cpp
	map_parse.cpp
	mathutil.cpp
	porting.cpp
	soundtool.cpp
	specials_parse.cpp
	tarball.cpp
	undo.cpp
	gzstream/gzstream.cpp
	resmgr/restypes.cpp
""")

if str(platform) == "darwin":
	tools.extend(Glob("*.mac.*"))
elif str(platform) == "win32":
	tools.extend(Glob("*.win.cpp"))

tools_obj = env.StaticLibrary("#build/lib/tools", tools)

Return("tools_obj")
